=== uo287791/uo287791.github.io/XML/rutas.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uniovi.es"
	xmlns="http://www.uniovi.es"
	elementFormDefault="qualified">	
	
	
	
	<xs:element name="rutas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="ruta" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="ruta">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="medio-transporte" />
				<xs:element minOccurs="0" maxOccurs="1" ref="fecha-inicio" />
				<xs:element minOccurs="1" maxOccurs="1" ref="hora-inicio" />
				<xs:element minOccurs="1" maxOccurs="1" ref="agencia" />
				<xs:element minOccurs="1" maxOccurs="1" ref="descripcion" />
				<xs:element minOccurs="1" maxOccurs="1" ref="accesibilidad" />
				<xs:element minOccurs="1" maxOccurs="1" ref="lugar-inicio" />
				<xs:element minOccurs="1" maxOccurs="1" ref="direccion-inicio" />
				<xs:element minOccurs="1" maxOccurs="1" ref="coordenadas-inicio" />
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="hito" />
			</xs:sequence>
			
			<xs:attribute name="nombre" type="xs:string" use="required"/>
			
			<xs:attribute name="rating" >
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="10"/>
					</xs:restriction>
				</xs:simpleType>
			
			</xs:attribute>

			<xs:attribute name="tipo-ruta" type="xs:string" />

			<xs:attribute name="tiempo-ruta" type="xs:duration" />

		</xs:complexType>
	</xs:element>

	<xs:element name="medio-transporte" type="xs:string" />
	<xs:element name="fecha-inicio" type="xs:date" />
	<xs:element name="hora-inicio" type="xs:time"/>
	<xs:element name="agencia" type="xs:string" />
	<xs:element name="descripcion" type="xs:string" />
	<xs:element name="accesibilidad" type="xs:string" />
	<xs:element name="lugar-inicio" type="xs:string" />
	<xs:element name="direccion-inicio" type="xs:string" />
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="descripcion-hito" type="xs:string" />
	<xs:element name="foto-hito" type="xs:string" />

	<xs:element name="hito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="descripcion-hito" />
				<xs:element ref="coordenadas-hito" />
				<xs:element ref="distancia-previo" />
				<xs:element minOccurs="1" maxOccurs="5" ref="foto-hito" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:ID" use="required" />
		</xs:complexType>
	</xs:element>


	<xs:element name="coordenadas-inicio">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="1" ref="latitud" />
				<xs:element minOccurs="1" maxOccurs="1" ref="longitud" />
				<xs:element minOccurs="1" maxOccurs="1" ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadas-hito">
		<xs:complexType>

			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="1" ref="longitud" />
				<xs:element minOccurs="1" maxOccurs="1" ref="latitud" />
				<xs:element minOccurs="1" maxOccurs="1" ref="altitud" />
			</xs:sequence>

		</xs:complexType>
	</xs:element>	

	<xs:element name="latitud" type="xs:double" />
	<xs:element name="longitud" type="xs:double" />
	<xs:element name="altitud" type="xs:double" />

	<xs:element name="distancia-previo" >
		<xs:complexType>
			<xs:sequence>
				<xs:element name="distancia" type="xs:integer"/>
			</xs:sequence>
			<xs:attribute name="unidades" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>




</xs:schema>

=== uo287791/uo287791.github.io/XML/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>

<rutas xmlns="http://www.uniovi.es"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uniovi.es rutas.xsd">

    <ruta nombre="Ruta turistica caracas" rating="10" tipo-ruta="Turistica" tiempo-ruta="PT7H">

        <medio-transporte>
            Autobus
        </medio-transporte>
        
        <fecha-inicio>
            2023-02-02
        </fecha-inicio>

        <hora-inicio>
            13:00:00
        </hora-inicio>

        <agencia>
            Agencias Caracas
        </agencia>

        <descripcion>
            Muy bonita
        </descripcion>

        <accesibilidad>
            Para todo el mundo
        </accesibilidad>

        <lugar-inicio>
            Plaza altamira
        </lugar-inicio>

        <direccion-inicio>
            Plaza altamira
        </direccion-inicio>

        <coordenadas-inicio>
            <latitud>10.4964</latitud>
            <longitud>-66.849</longitud>
            <altitud> 1303</altitud>
        </coordenadas-inicio>

        <referencia>
            www.google.es
        </referencia>      
        <referencia>
            www.venezuela.es
        </referencia>        
        <referencia>
            www.rutas.es
        </referencia>

        <hito nombre="Plaza Altamira">
            <descripcion-hito>
                Muy bonito
            </descripcion-hito>

            <coordenadas-hito>
                <longitud>-66.849</longitud>
                <latitud>10.4964</latitud>

                <altitud> 2000</altitud>

            </coordenadas-hito>

            <distancia-previo unidades="km">
               <distancia>
                    34 
               </distancia>
            </distancia-previo>

            <foto-hito>
                Altamira.jpg
            </foto-hito>
        </hito>

        <hito nombre="Parque Nacional El Avila">
            <descripcion-hito>
                Muy bonito
            </descripcion-hito>
            
            <coordenadas-hito>
               <longitud>-66.866666666667</longitud>
               <latitud>10.533333333333</latitud>

               <altitud> 1203</altitud>
            </coordenadas-hito>

            <distancia-previo unidades="km" >
               <distancia>
                    34 
               </distancia> 
            </distancia-previo>
            <foto-hito>
                avila.jpeg
            </foto-hito>
        </hito>

        <hito nombre="Casa Natal Simon Bolivar">
            <descripcion-hito>
                Muy bonito
            </descripcion-hito>
            
            <coordenadas-hito>
               <longitud>-66.916944444444</longitud>
               <latitud>10.495277777778</latitud>

               <altitud> 1123</altitud>

            </coordenadas-hito>

            <distancia-previo  unidades="km">
               <distancia>
                34
               </distancia>  
            </distancia-previo>

            <foto-hito>
                casa.jpeg
            </foto-hito>
       
       
        </hito>

        <hito nombre="Iglesia San Constantino">
            <descripcion-hito>
                Muy bonito
            </descripcion-hito>
             
            <coordenadas-hito>
               <longitud>-66.82132503068419</longitud>
               <latitud>10.418461107811947</latitud>

                <altitud> 2192</altitud>

            </coordenadas-hito>

            <distancia-previo  unidades="km">
              <distancia>34</distancia>  
            </distancia-previo>

            <foto-hito>
                Mifoto.jpg
            </foto-hito>
        </hito>




    </ruta>

    <ruta nombre="Ruta historica caracas" rating="10" tipo-ruta="Historica"  tiempo-ruta="PT7H">

    <medio-transporte>
        Autobus
    </medio-transporte>
    
    <fecha-inicio>
        2023-02-02
    </fecha-inicio>

    <hora-inicio>
        13:00:00
    </hora-inicio>

    <agencia>
        Agencias Caracas
    </agencia>

    <descripcion>
        Muy bonita
    </descripcion>

    <accesibilidad>
        Para todo el mundo
    </accesibilidad>

    <lugar-inicio>
       Quinta de anauco
    </lugar-inicio>

    <direccion-inicio>
        Quinta de Anauco,10
    </direccion-inicio>

    <coordenadas-inicio>
        <latitud>10.511762296954425</latitud>
        <longitud>-66.89932696217912</longitud>
        <altitud> 1533</altitud>
    </coordenadas-inicio>

    <referencia>
        www.google.es
    </referencia>      
    <referencia>
        www.venezuela.es
    </referencia>        
    <referencia>
        www.rutas.es
    </referencia>

        <hito nombre="Quinta de Anauco">
            <descripcion-hito>
                Muy bonito
            </descripcion-hito>
            
            <coordenadas-hito>
               <longitud>-66.89932696217912</longitud>
               <latitud>10.511762296954425</latitud>

               <altitud> 2342</altitud>

            </coordenadas-hito>

            <distancia-previo  unidades="km">
                <distancia>
                 34
                </distancia>  
             </distancia-previo>

            <foto-hito>
                anauco.jpg
            </foto-hito>
        </hito>

        <hito nombre="Panteon">
            <descripcion-hito>
                Muy bonito
            </descripcion-hito>
            
            <coordenadas-hito>
               <longitud>-66.91224425161853</longitud>
               <latitud>10.511858644985727</latitud>

               <altitud> 1247</altitud>

            </coordenadas-hito>

            <distancia-previo  unidades="km">
                <distancia>
                    34
                </distancia>  
             </distancia-previo>

            <foto-hito>
                panteon.jpg
            </foto-hito>
        </hito>


        <hito nombre="Iglesia de ChiquinquirÃ¡">
            <descripcion-hito>
                Muy bonito
            </descripcion-hito>
            
            <coordenadas-hito>
               <longitud>-66.89932696217912</longitud>
               <latitud>10.501846024680487</latitud>

               <altitud> 1782</altitud>

            </coordenadas-hito>

            <distancia-previo  unidades="km">
                <distancia>
                 34
                </distancia>  
             </distancia-previo>

            <foto-hito>
                iglesia.jpg
            </foto-hito>
        </hito>



    </ruta>

    <ruta nombre="Ruta naturaleza" rating="10" tipo-ruta="Naturaleza"  tiempo-ruta="PT7H">

       
    <medio-transporte>
        Autobus
    </medio-transporte>
    
    <fecha-inicio>
        2023-02-02
    </fecha-inicio>

    <hora-inicio>
        13:00:00
    </hora-inicio>

    <agencia>
        Agencias Caracas
    </agencia>

    <descripcion>
        Muy bonita
    </descripcion>

    <accesibilidad>
        Para todo el mundo
    </accesibilidad>

    <lugar-inicio>
        Parque Del Este     
    </lugar-inicio>

    <direccion-inicio>
        Parque Del Este, 10
    </direccion-inicio>

    <coordenadas-inicio>
        <latitud>10.511762296954425</latitud>
        <longitud>-66.89932696217912</longitud>
        <altitud> 1533</altitud>
    </coordenadas-inicio>

    <referencia>
        www.google.es
    </referencia>      
    <referencia>
        www.venezuela.es
    </referencia>        
    <referencia>
        www.rutas.es
    </referencia>

        <hito nombre="Parque del Este">
            <descripcion-hito>
                Muy bonito
            </descripcion-hito>
            
            <coordenadas-hito>
               <longitud>-66.8391922</longitud>
               <latitud>10.4923297</latitud>

                <altitud> 1233</altitud>

            </coordenadas-hito>

            <distancia-previo  unidades="km">
                <distancia>
                 34
                </distancia>  
             </distancia-previo>

            <foto-hito>
                este.jpg
            </foto-hito>
        </hito>

        <hito nombre="Expanzoo Recreacional">
            <descripcion-hito>
                Muy bonito
            </descripcion-hito>
            
            <coordenadas-hito>
               <longitud>-66.7855634232895</longitud>
               <latitud>10.423658099999997</latitud>

                <altitud> 1253</altitud>

            </coordenadas-hito>

            <distancia-previo  unidades="km">
                <distancia>
                 34
                </distancia>  
             </distancia-previo>

            <foto-hito>
                exopanzoo.jpg
            </foto-hito>
        </hito>


        <hito nombre="ParqueLosChorros">
            <descripcion-hito>
                Muy bonito
            </descripcion-hito>
    
            <coordenadas-hito>
               <longitud>-66.82489883665387</longitud>
               <latitud>10.507929093739738</latitud>

               <altitud> 809</altitud>

            </coordenadas-hito>

            <distancia-previo  unidades="km">
                <distancia>
                 34
                </distancia>  
             </distancia-previo>

            <foto-hito>
                chorros.jpg
            </foto-hito>
        </hito>




    </ruta>



    

</rutas>
